language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install python-igraph plotly ipywidgets
  - pip install pytest-cov

script:
  - pytest --cov kmapper

after_success:
  - bash <(curl -s https://codecov.io/bash)
